apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-scale-set-android
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "16"
spec:
  project: default
  source:
    repoURL: https://github.com/recomendapp/infra.git
    targetRevision: main
    path: cluster/services/actions-runner-scale-set-android
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
