apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcloud-volumes-patch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/recomendapp/infra.git'
    targetRevision: main
    path: cluster/services/hcloud-volumes-patch
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system 
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Force=true