apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pvc-autoresizer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://topolvm.github.io/pvc-autoresizer/'
    chart: pvc-autoresizer
    targetRevision: 0.15.1
    helm:
      valuesObject:
        controller:
          args:
            prometheusURL: "http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090"
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/metrics"
            prometheus.io/port: "8080"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: pvc-autoresizer

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true