apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umami-postgres-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: umami-postgres-secret
    creationPolicy: Owner

  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: UMAMI_DB_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: UMAMI_DB_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: UMAMI_DB_NAME