apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umami-postgres-data
spec:
  storageClassName: hcloud-volumes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi