apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 7.2.1
    chart: velero
    helm:
      valuesObject:
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.10.0
            volumeMounts:
              - mountPath: /target
                name: plugins

        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: placeholder
              config:
                region: auto
                s3ForcePathStyle: "true"
                s3Url: placeholder
              credential:
                name: cloud-credentials
                key: cloud
          
          volumeSnapshotLocation:
            - name: default
              provider: aws
              config:
                region: auto

          defaultBackupTTL: 720h
          defaultVolumesToFsBackup: true

        credentials:
          useSecret: true
          existingSecret: cloud-credentials

        schedules:
          daily:
            disabled: false
            schedule: "0 2 * * *"
            template:
              ttl: "720h"
              includedNamespaces:
                - "*"
              excludedNamespaces:
                - kube-system
              storageLocation: default
          
          weekly:
            disabled: false
            schedule: "0 3 * * 0"
            template:
              ttl: "2160h"
              includedNamespaces:
                - "*"
              excludedNamespaces:
                - kube-system
              storageLocation: default

        resources:
          requests:
            cpu: 500m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 512Mi

        deployNodeAgent: true
        nodeAgent:
          podVolumePath: /var/lib/kubelet/pods
          privileged: false
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi

        metrics:
          enabled: true
          serviceMonitor:
            enabled: false

        logLevel: info
        logFormat: text

  destination:
    server: https://kubernetes.default.svc
    namespace: velero

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m