apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: velero-s3-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .data.cloud.accessKey }}
          aws_secret_access_key={{ .data.cloud.secretKey }}

  data:
    - secretKey: cloud.accessKey
      remoteRef:
        key: VELERO_R2_ACCESS_KEY_ID
    - secretKey: cloud.secretKey
      remoteRef:
        key: VELERO_R2_SECRET_ACCESS_KEY
