apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: api-secret
    creationPolicy: Owner
  data:
    - secretKey: AUTH_SECRET
      remoteRef:
        key: AUTH_SECRET
    - secretKey: AUTH_GITHUB_CLIENT_ID
      remoteRef:
        key: AUTH_GITHUB_CLIENT_ID
    - secretKey: AUTH_GITHUB_CLIENT_SECRET
      remoteRef:
        key: AUTH_GITHUB_CLIENT_SECRET