apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: api-secret
    creationPolicy: Owner
  data:
    - secretKey: AUTH_COOKIE_DOMAIN
      remoteRef:
        key: AUTH_COOKIE_DOMAIN
    - secretKey: AUTH_SECRET
      remoteRef:
        key: AUTH_SECRET
    # Google
    - secretKey: AUTH_GOOGLE_CLIENT_ID
      remoteRef:
        key: AUTH_GOOGLE_CLIENT_ID
    - secretKey: AUTH_GOOGLE_CLIENT_SECRET
      remoteRef:
        key: AUTH_GOOGLE_CLIENT_SECRET
    # Github
    - secretKey: AUTH_GITHUB_CLIENT_ID
      remoteRef:
        key: AUTH_GITHUB_CLIENT_ID
    - secretKey: AUTH_GITHUB_CLIENT_SECRET
      remoteRef:
        key: AUTH_GITHUB_CLIENT_SECRET
    # Facebook
    - secretKey: AUTH_FACEBOOK_CLIENT_ID
      remoteRef:
        key: AUTH_FACEBOOK_CLIENT_ID
    - secretKey: AUTH_FACEBOOK_CLIENT_SECRET
      remoteRef:
        key: AUTH_FACEBOOK_CLIENT_SECRET
    # Apple
    - secretKey: AUTH_APPLE_CLIENT_ID
      remoteRef:
        key: AUTH_APPLE_CLIENT_ID
    - secretKey: AUTH_APPLE_TEAM_ID
      remoteRef:
        key: AUTH_APPLE_TEAM_ID
    - secretKey: AUTH_APPLE_KEY_ID
      remoteRef:
        key: AUTH_APPLE_KEY_ID
    - secretKey: AUTH_APPLE_PRIVATE_KEY
      remoteRef:
        key: AUTH_APPLE_PRIVATE_KEY
    - secretKey: AUTH_APPLE_BUNDLE_ID
      remoteRef:
        key: AUTH_APPLE_BUNDLE_ID