apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: martin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/recomendapp/infra.git
    targetRevision: main
    path: apps/martin
    directory:
      exclude: '{app.yaml,image-updater.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
