apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notify-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: notify-secret
    creationPolicy: Owner
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: REDIS_PASSWORD
    - secretKey: RESEND_API_KEY
      remoteRef:
        key: RESEND_API_KEY
    - secretKey: FIREBASE_PROJECT_ID
      remoteRef:
        key: FIREBASE_PROJECT_ID
    - secretKey: FIREBASE_CLIENT_EMAIL
      remoteRef:
        key: FIREBASE_CLIENT_EMAIL
    - secretKey: FIREBASE_PRIVATE_KEY_B64
      remoteRef:
        key: FIREBASE_PRIVATE_KEY_B64
    - secretKey: APNS_KEY_B64
      remoteRef:
        key: APNS_KEY_B64
    - secretKey: APNS_KEY_ID
      remoteRef:
        key: APNS_KEY_ID
    - secretKey: APNS_TEAM_ID
      remoteRef:
        key: APNS_TEAM_ID
    - secretKey: APNS_BUNDLE_ID
      remoteRef:
        key: APNS_BUNDLE_ID