apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      imagePullSecrets:
        - name: github-credentials
      containers:
        - name: auth
          image: ghcr.io/recomendapp/api-auth:20260124013806-05e581d
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: WEB_APP_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: WEB_APP_URL
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: SUPABASE_URL
            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: SUPABASE_ANON_KEY
            - name: SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: SUPABASE_SERVICE_ROLE_KEY
            - name: SUPABASE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: SUPABASE_JWT_SECRET
