apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    resources:
      requests:
        cpu: "300m"
        memory: "256Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"