apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  rewrites.server: |
    rewrite name api.recomend.app api.default.svc.cluster.local
    rewrite name imgproxy.recomend.app imgproxy.default.svc.cluster.local
    rewrite name martin.recomend.app martin.default.svc.cluster.local
    rewrite name notify.recomend.app notify.default.svc.cluster.local
    rewrite name prefect.recomend.app prefect.default.svc.cluster.local
    rewrite name typesense.recomend.app typesense.default.svc.cluster.local
    rewrite name umami.recomend.app umami.default.svc.cluster.local
    rewrite name web-app.recomend.app web-app.default.svc.cluster.local
