apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rustfs
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - medias.recomend.app
      secretName: rustfs-tls
  rules:
    - host: medias.recomend.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rustfs
                port:
                  number: 9000
