apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: rustfs-secret
    creationPolicy: Owner
  data:
    - secretKey: RUSTFS_ACCESS_KEY
      remoteRef:
        key: S3_ACCESS_KEY_ID
    - secretKey: RUSTFS_SECRET_KEY
      remoteRef:
        key: S3_SECRET_ACCESS_KEY
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        key: S3_ACCESS_KEY_ID
    - secretKey: S3_SECRET_ACCESS_KEY
      remoteRef:
        key: S3_SECRET_ACCESS_KEY
    - secretKey: S3_BUCKET
      remoteRef:
        key: S3_BUCKET
    - secretKey: S3_SITEMAPS_BUCKET
      remoteRef:
        key: S3_SITEMAPS_BUCKET
    - secretKey: S3_IMPORTS_BUCKET
      remoteRef:
        key: S3_IMPORTS_BUCKET
