apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      imagePullSecrets:
        - name: github-credentials
      containers:
        - name: web-app
          image: ghcr.io/recomendapp/web-app:20251218223638
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 10
            successThreshold: 1
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
              ephemeral-storage: "20Gi"
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=2048"
          envFrom:
            - secretRef:
                name: web-app-secret
