apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: web-app-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: web-app-secret
    creationPolicy: Owner

  data:
    - secretKey: NEXT_PUBLIC_SITE_URL
      remoteRef:
        key: WEB_APP_URL
    - secretKey: NEXT_SERVER_ACTIONS_ENCRYPTION_KEY
      remoteRef:
        key: WEB_APP_SERVER_ACTIONS_ENCRYPTION_KEY
    # ANALYTICS
    - secretKey: ANALYTICS_URL
      remoteRef:
        key: UMAMI_ANALYTICS_URL
    - secretKey: ANALYTICS_ID
      remoteRef:
        key: UMAMI_ANALYTICS_ID
    # REVENUECAT
    - secretKey: NEXT_PUBLIC_REVENUECAT_API_KEY
      remoteRef:
        key: REVENUECAT_API_KEY
    # FIREBASE
    - secretKey: NEXT_PUBLIC_FIREBASE_API_KEY
      remoteRef:
        key: FIREBASE_API_KEY
    - secretKey: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
      remoteRef:
        key: FIREBASE_AUTH_DOMAIN
    - secretKey: NEXT_PUBLIC_FIREBASE_PROJECT_ID
      remoteRef:
        key: FIREBASE_PROJECT_ID
    - secretKey: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
      remoteRef:
        key: FIREBASE_STORAGE_BUCKET
    - secretKey: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
      remoteRef:
        key: FIREBASE_MESSAGING_SENDER_ID
    - secretKey: NEXT_PUBLIC_FIREBASE_APP_ID
      remoteRef:
        key: FIREBASE_APP_ID
    - secretKey: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
      remoteRef:
        key: FIREBASE_MEASUREMENT_ID
    - secretKey: NEXT_PUBLIC_FIREBASE_FCM_VAPID_KEY
      remoteRef:
        key: FIREBASE_FCM_VAPID_KEY
    # TMDB
    - secretKey: NEXT_PUBLIC_TMDB_IMAGE_BASE_URL
      remoteRef:
        key: TMDB_IMAGE_BASE_URL
    # JUSTWATCH
    - secretKey: NEXT_PUBLIC_JUSTWATCH_API_KEY
      remoteRef:
        key: JUSTWATCH_API_KEY
    # CLOUDFLARE
    - secretKey: NEXT_PUBLIC_TURNSTILE_SITE_KEY
      remoteRef:
        key: CLOUDFLARE_TURNSTILE_SITE_KEY
    - secretKey: TURNSTILE_SECRET_KEY
      remoteRef:
        key: CLOUDFLARE_TURNSTILE_SECRET_KEY
    # ---------------------------------- MOBILE ---------------------------------- #
    - secretKey: ANDROID_PACKAGE_NAME
      remoteRef:
        key: ANDROID_PACKAGE_NAME
    - secretKey: ANDROID_SHA256_FINGERPRINTS
      remoteRef:
        key: ANDROID_SHA256_FINGERPRINTS
    - secretKey: IOS_APPLE_TEAM_ID
      remoteRef:
        key: IOS_APPLE_TEAM_ID
    - secretKey: IOS_BUNDLE_ID
      remoteRef:
        key: IOS_BUNDLE_ID
