apiVersion: batch/v1
kind: Job
metadata:
  name: prefect-init
  namespace: prefect
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: prefecthq/prefect:3-latest
          env:
            - name: PREFECT_API_URL
              value: "http://prefect-server.prefect.svc.cluster.local:4200/api"
            - name: PREFECT_API_AUTH_STRING
              valueFrom:
                secretKeyRef:
                  name: prefect-auth-secret
                  key: auth-string

            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token-secret
                  key: token

          command:
            - /bin/sh
            - -c
            - |
              apt-get update && apt-get install -y curl
              pip install prefect-github -q

              echo "Waiting for Prefect API..."
              until curl -sf "${PREFECT_API_URL}/health"; do
                sleep 2
                echo "Still waiting for Prefect API..."
              done

              python3 -c "
              from prefect_github import GitHubCredentials
              import os

              github_token = os.environ['GITHUB_TOKEN']
              print(f'Creating GitHub block with token: {github_token[:4]}****')
              GitHubCredentials(token=github_token).save('github-credentials')
              print('GitHub block created')

              "
