apiVersion: batch/v1
kind: Job
metadata:
  name: prefect-init
  namespace: prefect
  # annotations:
  #   argocd.argoproj.io/hook: PostSync
  #   argocd.argoproj.io/hook-delete-policy: HookSucceeded

spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: prefecthq/prefect:3-latest
          env:
            - name: PREFECT_API_URL
              value: "http://prefect-server.prefect.svc.cluster.local:4200/api"

            - name: PREFECT_API_AUTH_STRING
              valueFrom:
                secretKeyRef:
                  name: prefect-auth-secret
                  key: auth-string

            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: prefect-secrets
                  key: GITHUB_TOKEN

            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: prefect-secrets
                  key: TYPESENSE_API_KEY

            - name: TYPESENSE_HOST
              value: "typesense.default.svc.cluster.local"

            - name: TYPESENSE_PORT
              value: "8108"

            - name: TYPESENSE_PROTOCOL
              value: "http"

            - name: SUPABASE_POSTGRES_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: prefect-secrets
                  key: SUPABASE_POSTGRES_CONNECTION_STRING

            - name: TMDB_API_KEYS
              valueFrom:
                secretKeyRef:
                  name: prefect-secrets
                  key: TMDB_API_KEYS

          command:
            - /bin/sh
            - -c
            - |
              apt-get update && apt-get install -y curl
              pip install prefect-github -q

              echo "Waiting for Prefect API..."
              until curl -sf "${PREFECT_API_URL}/health"; do
                sleep 2
                echo "Still waiting for Prefect API..."
              done

              python3 - <<'EOF'
              from prefect_github import GitHubCredentials
              from prefect.blocks.system import Secret
              import os

              # ---------------------
              # GitHub Credentials Block
              # ---------------------
              print("Creating GitHub block...")
              github_token = os.environ["GITHUB_TOKEN"]
              GitHubCredentials(token=github_token).save("github-credentials", overwrite=True)
              print("GitHub block created.")

              # ---------------------
              # Typesense Blocks
              # ---------------------
              print("Creating Typesense blocks...")

              Secret(value=os.environ["TYPESENSE_API_KEY"]).save(
                  "typesense-api-key", overwrite=True
              )
              Secret(value=os.environ["TYPESENSE_HOST"]).save(
                  "typesense-host", overwrite=True
              )
              Secret(value=os.environ["TYPESENSE_PORT"]).save(
                  "typesense-port", overwrite=True
              )
              Secret(value=os.environ["TYPESENSE_PROTOCOL"]).save(
                  "typesense-protocol", overwrite=True
              )

              print("Typesense blocks created.")

              # ---------------------
              # Supabase Postgres Block
              # ---------------------
              print("Creating Supabase Postgres block...")

              Secret(value=os.environ["SUPABASE_POSTGRES_CONNECTION_STRING"]).save(
                  "postgres-connection-string",
                  overwrite=True
              )

              print("Supabase block created.")

              # ---------------------
              # TMDB Block
              # ---------------------
              print("Creating TMDB block...")

              Secret(value=os.environ["TMDB_API_KEYS"]).save(
                  "tmdb-api-key",
                  overwrite=True
              )

              print("TMDB block created.")

              print("Init job completed successfully.")
              EOF
