apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prefect-auth-secret
  namespace: prefect
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: prefect-auth-secret
    creationPolicy: Owner

  data:
    - secretKey: auth-string
      remoteRef:
        key: PREFECT_AUTH_STRING
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prefect-secrets
  namespace: prefect
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: prefect-secrets
    creationPolicy: Owner

  data:
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: GITHUB_TOKEN

    - secretKey: TYPESENSE_API_KEY
      remoteRef:
        key: TYPESENSE_API_KEY
        
    - secretKey: WEB_APP_URL
      remoteRef:
        key: WEB_APP_URL

    - secretKey: POSTGRES_USER
      remoteRef:
        key: DB_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: DB_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: DB_NAME

    - secretKey: TMDB_API_KEYS
      remoteRef:
        key: TMDB_API_KEYS

    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: S3_ACCESS_KEY_ID
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: S3_SECRET_ACCESS_KEY
    - secretKey: S3_SITEMAPS_BUCKET
      remoteRef:
        key: S3_SITEMAPS_BUCKET
    - secretKey: S3_IMPORTS_BUCKET
      remoteRef:
        key: S3_IMPORTS_BUCKET

    - secretKey: API_INTERNAL_IMPORTS_SECRET
      remoteRef:
        key: API_INTERNAL_IMPORTS_SECRET

    - secretKey: API_INTERNAL_VERSION_POLICY_SECRET
      remoteRef:
        key: API_INTERNAL_VERSION_POLICY_SECRET

    - secretKey: APP_STORE_CONNECT_KEY_ID
      remoteRef:
        key: APP_STORE_CONNECT_KEY_ID
    - secretKey: APP_STORE_CONNECT_ISSUER_ID
      remoteRef:
        key: APP_STORE_CONNECT_ISSUER_ID
    - secretKey: APP_STORE_CONNECT_PRIVATE_KEY
      remoteRef:
        key: APP_STORE_CONNECT_PRIVATE_KEY
    - secretKey: APP_STORE_CONNECT_APP_ID
      remoteRef:
        key: APP_STORE_CONNECT_APP_ID

    - secretKey: GOOGLE_PLAY_PACKAGE_NAME
      remoteRef:
        key: GOOGLE_PLAY_PACKAGE_NAME
    - secretKey: GOOGLE_PLAY_SERVICE_ACCOUNT_JSON
      remoteRef:
        key: GOOGLE_PLAY_SERVICE_ACCOUNT_JSON
