apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: typesense
spec:
  serviceName: typesense
  replicas: 1
  selector:
    matchLabels:
      app: typesense
  template:
    metadata:
      # Don't backup Typesense data as it's rebuildable
      # annotations:
      #   backup.velero.io/backup-volumes: data
      labels:
        app: typesense
    spec:
      initContainers:
        - name: init-typesense-schema
          image: curlimages/curl:8.0
          command:
            - sh
            - -c
            - |
              echo "Waiting for Typesense..."
              until curl -s http://typesense:8108/health; do sleep 2; done

              for f in /schema/*.json; do
                echo "Applying $f ..."
                curl -s -X POST "http://typesense:8108/collections" \
                  -H "Content-Type: application/json" \
                  -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
                  --data @$f \
                || echo "-> Already exists, skipping"
              done

              echo "Init OK"
          env:
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: typesense-secret
                  key: TYPESENSE_API_KEY
          volumeMounts:
            - name: schema
              mountPath: /schema

      containers:
      - name: typesense
        image: typesense/typesense:29.0
        args:
          - "--data-dir=/data"
          - "--api-key=$(TYPESENSE_API_KEY)"
          - "--enable-cors=false"
        env:
        - name: TYPESENSE_API_KEY
          valueFrom:
            secretKeyRef:
              name: typesense-secret
              key: TYPESENSE_API_KEY
        ports:
        - containerPort: 8108
          name: http
        volumeMounts:
        - name: data
          mountPath: /data

      volumes:
        - name: schema
          configMap:
            name: typesense-schemas

  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        resize.topolvm.io/storage_limit: "20Gi"
        resize.topolvm.io/threshold: "20%"
        resize.topolvm.io/increase: "25%"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: hcloud-volumes
      resources:
        requests:
          storage: 10Gi
