apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imgproxy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/recomendapp/infra.git
    targetRevision: main
    path: apps/services/imgproxy
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
