apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prefect
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://prefecthq.github.io/prefect-helm
      chart: prefect-server
      targetRevision: 2025.11.21180339
      helm:
        valuesObject:

          api:
            replicaCount: 1

          ui:
            replicaCount: 1
            ingress:
              enabled: true
              className: traefik
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-staging
              hosts:
                - host: prefect.recomend.app
                  paths:
                    - path: /
                      pathType: Prefix
              tls:
                - secretName: prefect-tls
                  hosts:
                    - prefect.recomend.app

          postgresql:
            enabled: true
            primary:
              persistence:
                enabled: true
                storageClass: hcloud-volumes
                size: 10Gi
                annotations:
                  resize.topolvm.io/storage_limit: "50Gi"
                  resize.topolvm.io/threshold: "20%"
                  resize.topolvm.io/increase: "25%"
                  backup.velero.io/backup-volumes: "data"

  destination:
    server: https://kubernetes.default.svc
    namespace: prefect

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
