apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prefect
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://prefecthq.github.io/prefect-helm
      chart: prefect-server
      targetRevision: 2025.11.21180339
      helm:
        valuesObject:

          api:
            replicaCount: 1
            env:
              - name: PREFECT_UI_API_URL
                value: "https://prefect.recomend.app/api"

          ui:
            replicaCount: 1
            env:
              - name: PREFECT_UI_API_URL
                value: "https://prefect.recomend.app/api"
            service:
              port: 4200

          postgresql:
            enabled: true
            primary:
              persistence:
                enabled: true
                storageClass: hcloud-volumes
                size: 10Gi
                annotations:
                  resize.topolvm.io/storage_limit: "50Gi"
                  resize.topolvm.io/threshold: "20%"
                  resize.topolvm.io/increase: "25%"
                  backup.velero.io/backup-volumes: "data"

    - repoURL: https://prefecthq.github.io/prefect-helm
      chart: prefect-worker
      targetRevision: 2025.11.21180339
      helm:
        valuesObject:
          worker:
            apiConfig: selfHostedServer
            config:
              workPool: kube
            selfHostedServerApiConfig:
              apiUrl: "http://prefect-server.prefect.svc.cluster.local:4200/api"

    - repoURL: https://github.com/recomendapp/infra.git
      targetRevision: main
      path: apps/services/prefect
      directory:
        recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: prefect

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
