apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-secrets
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: monitoring-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        ALERTMANAGER_DISCORD_WEBHOOK_URL: "{{ .ALERTMANAGER_DISCORD_WEBHOOK_URL }}"
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
          inhibit_rules:
            - source_matchers:
                - 'severity = critical'
              target_matchers:
                - 'severity =~ warning|info'
              equal:
                - 'namespace'
                - 'alertname'
            - source_matchers:
                - 'severity = warning'
              target_matchers:
                - 'severity = info'
              equal:
                - 'namespace'
                - 'alertname'
            - source_matchers:
                - 'alertname = InfoInhibitor'
              target_matchers:
                - 'severity = info'
              equal:
                - 'namespace'
            - target_matchers:
                - 'alertname = InfoInhibitor'
          route:
            group_by: ['namespace', 'alertname']
            group_wait: 30s
            group_interval: 5m
            repeat_interval: 12h
            receiver: discord-webhook
            routes:
              - receiver: 'null'
                matchers:
                  - alertname = "Watchdog"
          receivers:
            - name: 'null'
            - name: discord-webhook
              discord_configs:
                - webhook_url: '{{ .ALERTMANAGER_DISCORD_WEBHOOK_URL }}'

  data:
    - secretKey: ALERTMANAGER_DISCORD_WEBHOOK_URL
      remoteRef:
        key: ALERTMANAGER_DISCORD_WEBHOOK_URL
