apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-secrets
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: monitoring-secrets
    creationPolicy: Owner
    template:
      type: Opaque

  data:
    - secretKey: ALERTMANAGER_DISCORD_WEBHOOK_URL
      remoteRef:
        key: ALERTMANAGER_DISCORD_WEBHOOK_URL
