apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-secrets
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: supabase-secrets
    creationPolicy: Owner
  data:
    # Supabase JWT
    - secretKey: anon-key
      remoteRef:
        key: SUPABASE_ANON_KEY
    - secretKey: service-role-key
      remoteRef:
        key: SUPABASE_SERVICE_ROLE_KEY
    - secretKey: jwt-secret
      remoteRef:
        key: SUPABASE_JWT_SECRET

    # Supabase DB
    - secretKey: postgres-password
      remoteRef:
        key: SUPABASE_POSTGRES_PASSWORD

    # Supabase SMTP
    - secretKey: smtp-username
      remoteRef:
        key: SUPABASE_SMTP_USERNAME
    - secretKey: smtp-password
      remoteRef:
        key: SUPABASE_SMTP_PASSWORD

    # Supabase Dashboard
    - secretKey: dashboard-username
      remoteRef:
        key: SUPABASE_DASHBOARD_USERNAME
    - secretKey: dashboard-password
      remoteRef:
        key: SUPABASE_DASHBOARD_PASSWORD
    - secretKey: openai-api-key
      remoteRef:
        key: SUPABASE_OPENAI_API_KEY
        
    # Supabase Analytics
    - secretKey: logflare-public-access-token
      remoteRef:
        key: SUPABASE_LOGFLARE_PUBLIC_ACCESS_TOKEN
    - secretKey: logflare-private-access-token
      remoteRef:
        key: SUPABASE_LOGFLARE_PRIVATE_ACCESS_TOKEN

    # Supabase Realtime
    - secretKey: realtime-secret
      remoteRef:
        key: SUPABASE_REALTIME_SECRET

    # Supabase Meta
    - secretKey: meta-crypto-key
      remoteRef:
        key: SUPABASE_META_CRYPTO_KEY

    # Supabase Supavisor
    - secretKey: supavisor-secret-key-base
      remoteRef:
        key: SUPABASE_SUPAVISOR_SECRET_KEY_BASE
    - secretKey: supavisor-vault-enc-key
      remoteRef:
        key: SUPABASE_SUPAVISOR_VAULT_ENC_KEY
