apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-r2-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: postgres-r2-secret
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: AWS_ACCESS_KEY_ID 
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: AWS_SECRET_ACCESS_KEY
    - secretKey: S3_BUCKET
      remoteRef:
        key: AWS_BUCKET
    - secretKey: S3_ENDPOINT
      remoteRef:
        key: AWS_ENDPOINT